version: "3"

services:
  app:
    volumes:
      - .:/app
    ports:
      - 3000:3000

  caddy:
    volumes:
      - .:/app
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
