# Отличается от docker-example-app, так как он собирается через Docker Compose
# https://github.com/docker/build-push-action
name: main

on:
  push:
    branches:
      - 'main'

env: # тег, под которым будет храниться временный образ-кеш
  TEST_TAG: vasilevpg/devops-example-app:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v2

      # Ниже список шагов из документации build-push-action
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        # Эти секреты нужно добавить самостоятельно
        # Получить https://docs.docker.com/docker-hub/access-tokens/
        # Добавить https://docs.github.com/en/actions/security-guides/encrypted-secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Сборка и сразу кеширование, чтобы повторный запуск был быстрее
      - uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      # Запуск тестов, команда запуска зависит от стека
      # Лучше ее спрятать за make
      - run: docker run --rm ${{ env.TEST_TAG }} npm test
      # Здесь же нужно настроить запуск линтера

      # Заливаем протестированный образ на Docker Hub
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vasilevpg/devops-example-app:latest


      # Добавляем сразу после сборки app
      - name: Build and push caddy
        uses: docker/build-push-action@v2
        with:
          context: .
          file: services/caddy/Dockerfile
          push: true
          # Не забудьте создать репозиторий в Docker Hub
          tags: vasilevpg/devops-example-caddy:latest